<?php
$dllist = array (
  0 => 'file/admin/app/weixin/accounts.html',
  1 => 'file/admin/app/weixin/accounts.php',
  2 => 'file/admin/app/weixin/accountseditor.html',
  3 => 'file/admin/app/weixin/accountseditor.php',
  4 => 'file/admin/app/weixin/accountseditorsave.php',
  5 => 'file/admin/app/weixin/delapp.php',
  6 => 'file/admin/app/weixin/export.func.php',
  7 => 'file/admin/app/weixin/help.html',
  8 => 'file/admin/app/weixin/help.php',
  9 => 'file/admin/app/weixin/index.html',
  10 => 'file/admin/app/weixin/index.php',
  11 => 'file/admin/app/weixin/indexeditor.html',
  12 => 'file/admin/app/weixin/indexeditor.php',
  13 => 'file/admin/app/weixin/indexsave.php',
  14 => 'file/admin/app/weixin/is_weixin.php',
  15 => 'file/admin/app/weixin/reply.html',
  16 => 'file/admin/app/weixin/reply.php',
  17 => 'file/admin/app/weixin/replyeditor.html',
  18 => 'file/admin/app/weixin/replyeditor.php',
  19 => 'file/admin/app/weixin/replysave.php',
  20 => 'file/admin/app/weixin/setapp.html',
  21 => 'file/admin/app/weixin/setapp.php',
  22 => 'file/admin/app/weixin/tmp/motop.html',
  23 => 'file/admin/app/weixin/token.php',
  24 => 'file/admin/app/weixin/top.html',
  25 => 'file/admin/app/weixin/weixin.php',
  26 => 'file/include/interface/weixin.php',
  27 => 'file/include/interface/wx.class.php',
  28 => 'file/public/app/weixin/image/weixin.jpg',
  29 => 'install.class.php',
)
?>